/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2022-03-24 09:34:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addProductView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>상품등록</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/admin.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../javascript/calendar.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("function fncAddProduct(){\r\n");
      out.write("	//Form 유효성 검증\r\n");
      out.write(" 	var name = document.detailForm.prodName.value;\r\n");
      out.write("	var detail = document.detailForm.prodDetail.value;\r\n");
      out.write("	var manuDate = document.detailForm.manuDate.value;\r\n");
      out.write("	var price = document.detailForm.price.value;\r\n");
      out.write("\r\n");
      out.write("	if(name == null || name.length<1){\r\n");
      out.write("		alert(\"상품명은 반드시 입력하여야 합니다.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(detail == null || detail.length<1){\r\n");
      out.write("		alert(\"상품상세정보는 반드시 입력하여야 합니다.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(manuDate == null || manuDate.length<1){\r\n");
      out.write("		alert(\"제조일자는 반드시 입력하셔야 합니다.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("	if(price == null || price.length<1){\r\n");
      out.write("		alert(\"가격은 반드시 입력하셔야 합니다.\");\r\n");
      out.write("		return;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	document.detailForm.action='/addProduct.do';\r\n");
      out.write("	document.detailForm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function resetData(){\r\n");
      out.write("	document.detailForm.reset();\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#ffffff\" text=\"#000000\">\r\n");
      out.write("\r\n");
      out.write("<form name=\"detailForm\" method=\"post\" >\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" height=\"37\" border=\"0\" cellpadding=\"0\"	cellspacing=\"0\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"15\" height=\"37\">\r\n");
      out.write("			<img src=\"/images/ct_ttl_img01.gif\" width=\"15\" height=\"37\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td background=\"/images/ct_ttl_img02.gif\" width=\"100%\" style=\"padding-left: 10px;\">\r\n");
      out.write("			<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"93%\" class=\"ct_ttl01\">상품등록</td>\r\n");
      out.write("					<td width=\"20%\" align=\"right\">&nbsp;</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td width=\"12\" height=\"37\">\r\n");
      out.write("			<img src=\"/images/ct_ttl_img03.gif\"	width=\"12\" height=\"37\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"	style=\"margin-top: 13px;\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("			상품명 <imgsrc=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\">\r\n");
      out.write("		</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">\r\n");
      out.write("			<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"105\">\r\n");
      out.write("						<input type=\"text\" name=\"prodName\" class=\"ct_input_g\" \r\n");
      out.write("									style=\"width: 100px; height: 19px\" maxLength=\"20\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("			상품상세정보 <img	src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">\r\n");
      out.write("			<input type=\"text\" name=\"prodDetail\" class=\"ct_input_g\" \r\n");
      out.write("						style=\"width: 100px; height: 19px\" maxLength=\"10\" minLength=\"6\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("			제조일자 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">\r\n");
      out.write("			<input type=\"text\" name=\"manuDate\" readonly=\"readonly\" class=\"ct_input_g\"  \r\n");
      out.write("						style=\"width: 100px; height: 19px\"	maxLength=\"10\" minLength=\"6\"/>\r\n");
      out.write("				&nbsp;<img src=\"../images/ct_icon_date.gif\" width=\"15\" height=\"15\" \r\n");
      out.write("										onclick=\"show_calendar('document.detailForm.manuDate', document.detailForm.manuDate.value)\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">\r\n");
      out.write("			가격 <img src=\"/images/ct_icon_red.gif\" width=\"3\" height=\"3\" align=\"absmiddle\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">\r\n");
      out.write("			<input type=\"text\" name=\"price\" 	class=\"ct_input_g\" \r\n");
      out.write("						style=\"width: 100px; height: 19px\" maxLength=\"10\">&nbsp;원\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"104\" class=\"ct_write\">상품이미지</td>\r\n");
      out.write("		<td bgcolor=\"D6D6D6\" width=\"1\"></td>\r\n");
      out.write("		<td class=\"ct_write01\">\r\n");
      out.write("			<input		type=\"text\" name=\"fileName\" class=\"ct_input_g\" \r\n");
      out.write("							style=\"width: 200px; height: 19px\" maxLength=\"13\"/>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td height=\"1\" colspan=\"3\" bgcolor=\"D6D6D6\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"	style=\"margin-top: 10px;\">\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td width=\"53%\"></td>\r\n");
      out.write("		<td align=\"right\">\r\n");
      out.write("		<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td width=\"17\" height=\"23\">\r\n");
      out.write("					<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\"  style=\"padding-top: 3px;\">\r\n");
      out.write("					<a href=\"javascript:fncAddProduct();\">등록</a>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=\"14\" height=\"23\">\r\n");
      out.write("					<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=\"30\"></td>\r\n");
      out.write("				<td width=\"17\" height=\"23\">\r\n");
      out.write("					<img src=\"/images/ct_btnbg01.gif\" width=\"17\" height=\"23\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td background=\"/images/ct_btnbg02.gif\" class=\"ct_btn01\"	 style=\"padding-top: 3px;\">\r\n");
      out.write("					<a href=\"javascript:resetData();\">취소</a>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td width=\"14\" height=\"23\">\r\n");
      out.write("					<img src=\"/images/ct_btnbg03.gif\" width=\"14\" height=\"23\"/>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
